
export const COLLEGES = [
  { college: "College of Accountancy", departments: ["Accountancy", "Accounting Information System"] },
  { college: "College of Agriculture", departments: ["Agriculture"] },
  { college: "College of Arts and Sciences", departments: ["Economics", "Political Science", "Biology", "Psychology", "Public Administration"] },
  { college: "College of Business Administration", departments: ["Financial Management", "Human Resource Development Management", "Legal Management", "Marketing Management", "Entrepreneurship", "Real Estate Management"] },
  { college: "College of Communication", departments: ["Communication"] },
  { college: "College of Informatics and Computing Studies", departments: ["Computing Studies"] },
  { college: "College of Criminology", departments: ["Criminology"] },
  { college: "College of Education", departments: ["Secondary Education", "Elementary Education", "Teacher Education"] },
  { college: "College of Engineering and Architecture", departments: ["Civil Engineering", "Electronics Engineering", "Electrical Engineering", "Industrial Engineering", "Mechanical Engineering", "Architecture", "BS Astronomy"] },
  { college: "College of Law", departments: ["Law"] },
  { college: "College of Medical Technology", departments: ["Medical Technology"] },
  { college: "College of Medicine", departments: ["Medicine"] },
  { college: "College of Midwifery", departments: ["Midwifery"] },
  { college: "College of Music", departments: ["Music"] },
  { college: "College of Nursing", departments: ["Nursing"] },
  { college: "College of Physical Therapy", departments: ["Physical Therapy"] },
  { college: "College of Respiratory Therapy", departments: ["Respiratory Therapy"] },
  { college: "School of International Relations", departments: ["International Relations"] },
  { college: "School of Graduate Studies", departments: ["Graduate Studies"] },
  { college: "Integrated School - Academic Track", departments: ["GAS", "STEM", "ABM", "HUMSS"] },
  { college: "Integrated School - TVL Track", departments: ["ICT", "Home Economics"] },
  { college: "Integrated School - Arts and Design Track", departments: ["Media/Visual Arts", "Literary/Theater Arts", "Music"] },
  { college: "NEUVLE +5", departments: ["NEUVLE"] },
];
